<?php

/**
 * Credit Card Validation Solution, PHP Edition,
 * Mensajes de error españoles de la lengua.
 *
 * @package    CreditCardValidationSolution
 * @author     Daniel Convissor <danielc@analysisandsolutions.com>
 * @copyright  The Analysis and Solutions Company, 2002-2006
 * @version    $Name: rel-5-14 $ $Id: ccvs_es.inc,v 1.3 2006/03/18 17:31:31 danielc Exp $
 * @link       http://www.analysisandsolutions.com/software/ccvs/ccvs.htm
 */

/** */
$CCVSErrNumberString = 'Número no es una secuencia';
$CCVSErrVisa14       = 'Visa tiene generalmente 16 o 13 dígitos, pero usted introdujo 14';
$CCVSErrUnknown      = 'Los primeros cuatro dígitos, %s, indican el tipo desconocido de la tarjeta';
$CCVSErrAccepted     = 'Programador utilizó incorrectamente la discusión aceptada';
$CCVSErrNoAccept     = 'No aceptamos tarjetas de %s';
$CCVSErrShort        = 'Número está faltando %s dígito(s)';
$CCVSErrLong         = 'Número tiene %s también muchos dígito(s)';
$CCVSErrChecksum     = 'Número falló en la prueba de suma de comprobación';
$CCVSErrMonthString  = 'Mes no es una secuencia';
$CCVSErrMonthFormat  = 'Mes tiene formato inválido';
$CCVSErrYearString   = 'Año no es una secuencia';
$CCVSErrYearFormat   = 'Año tiene formato inválido';
$CCVSErrExpired      = 'Tarjeta ha expirado';
